#!/bin/bash

# Downlaod picrust files
download_picrust_files.py

# Download and install qiime environment
wget https://data.qiime2.org/distro/core/qiime2-2018.6-py35-linux-conda.yml
conda env create -n qiime2 --file qiime2-2018.6-py35-linux-conda.yml
# OPTIONAL CLEANUP
rm qiime2-2018.6-py35-linux-conda.yml